<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>volleyball_pid_camera</name>
  <version>0.0.0</version>
  <description>USB Camera PID visual servoing node - detects volleyball and publishes pixel offset</description>
  <maintainer email="18020999493@163.com">xiaofeiyu</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>cv_bridge</depend>
  <depend>vision_opencv</depend>
  <depend>ament_index_cpp</depend>
  <depend>volleyball_interfaces</depend>
  <depend>volleyball_detect</depend>
  <depend>image_transport</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
