<package format="2">
  <name>volleyball_robot_description</name>
  <version>1.0.0</version>
  <description>
    <p>URDF Description package for volleyball_robot_description</p>
    <p>This package contains configuration data, 3D models and launch files
for volleyball_robot_description robot</p>
  </description>
  <author>TODO</author>
  <maintainer email="TODO@email.com" />
  <license>BSD</license>
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Runtime tools commonly used with description packages in ROS 2 -->
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher_gui</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>xacro</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
