
services:
  volleyball:
    image: volleyball-robot:latest
    container_name: volleyball-robot
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    restart: unless-stopped   # 👈 开机自启 + 挂了自动重启

    volumes:
      - ./src:/workspace_volleyball_robot/src
    
    command: >
      bash -c "
      source install/setup.bash &&
      echo '✅ 环境已加载' &&
      ros2 launch volleyball_robot bringup.launch.py
      "
    