ibvs_controller_node:
  ros__parameters:
    Kp_lat: 6057.0        # 横向比例增益 (cm/s)/m（strike_point系 y, 1m→6057cm/s）
    Kp_long: 500.0         # 纵向比例增益 (cm/s)/m，3m→1500cm/s，1m→500cm/s
    Kd_lat: 160.0           # 横向微分增益 cm/s² per m/s（y变化率→速度修正）
    alpha: 0.75           # EMA 平滑系数 (0~1)
    timeout: 0.5         # 看门狗超时 (s)
    hit_offset_x: 0.60      # 击球点 X 轴范围（前方），单位 m
    hit_offset_y: 0.35      # 击球点 Y 轴范围（横向），单位 m
    hit_offset_z: 0.3      # 击球点 Z 轴范围（高度），单位 m
    dist_offset: 0.35       
    target_frame: "strike_point"

#检测节点
detector_node:
  ros__parameters:
    model_path: "model/volleyball_v3_3_int8/best.xml"
    model_confidence_threshold : 0.6
    model_nms_threshold : 0.45
    depth_validation_threshold : 0.5
    debug : true
    camera_frame_id : "camera_color_optical_frame"
    debug_frame_skip: 3

#串口节点
serial_driver_node:
  ros__parameters:
    timestamp_offset: 0.005
    device_name: "/dev/ttyACM0"
    baud_rate: 115200
    odom_frame_id: "odom"
    base_link_frame_id: "base_link"
    # 下位机→上位机坐标系转换参数,单位deg度
    # 下位机: x右 y前, 上位机: x前 y右
    odom2base_rpy: [0.0, 0.0, 90.0]
